### ISSUE TITLE
Intellij does not recognize Java source as source files

### ISSUE THREAD

**Issue by jfelrod1960** [Renanse/Ardor3D#90]
When I open Ardor3D as a gradle project it downloads Gradle 6.0.1 and gives the following error:

<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>C:\Users\JFE\GitHub\Temp\Ardor3D\build.gradle<ij_nav><i><b>root project 'ardor3d': Unable to resolve additional project configuration.</b><eol>Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':ardor3d-examples:runtimeClasspath'.<eol>Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find lwjgl-opengl-3.2.3-natives-${platform}.jar (org.lwjgl:lwjgl-opengl:3.2.3).<eol>Searched in the following locations:<eol>    https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-${platform}.jar</i>

It does not recognize the Java code as source code.  The version of A3D I'm currently using does not contain the new module ardor3d-lwjgl3-awt.  It loads fine and I can study the examples.  With this version I can't run any of the examples. :( The new module may not be making the difference, but it is a suspect.  Appreciate any help.  Thanks!

**Comment by Renanse** [comment]
I'm not sure how to help here because I do not know where this ${platform} is coming in from.  You can see here that those files exist for various platforms though: https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/

None of the Ardor3D gradle files use "platform" as a variable.  You'll see in the build.gradle for ardor3d-lwjgl3 that we refer to the natives by:
	implementation "org.lwjgl:lwjgl-opengl:$lwjglVersion:$lwjglNatives"

Also, our CI service appears to be downloading and running the gradle build ok from scratch: https://travis-ci.org/Renanse/Ardor3D

**Comment by jfelrod1960** [comment]
Hey Josh ... It has something to do with the new ardor3d-lwjgl3-awt module.  When I removed that module and Java sources that depended on it, I was able to run the examples.  I was able to run the BoxExample and the PBR examples. :(

**Comment by Renanse** [comment]
So, it looks like some IDEs are having issues importing a dependency that uses maven profiles to set properties.  In this case, https://search.maven.org/artifact/org.lwjglx/lwjgl3-awt/0.1.7/jar  (see pom)

I'll skirt around the issue for folks on such IDEs by including the lwjglx/lwjgl3-awt jar.
